### ISSUE TITLE
o365 is stuck on "Trying to sign you in' page

### ISSUE THREAD

**Issue by lacylau157** [kgretzky/evilginx2#750] opened 2022-03-22 05:26 UTC
Just discovered o365 phishlet stuck on the "Trying to sign you in" page in an endless loop. A fix will be highly appreciated

**Comment by Caprico1** [comment] 2022-03-28 16:47
Seeing the same here.

**Comment by gsmthconsult** [comment] 2022-03-29 13:50
having same issue for over 10days now. What could be the problem ? any fix yet ?

**Comment by JM-Lemmi** [comment] 2022-03-29 17:12
I am also having the same issue. You can press the "cancel" button to get to sign-in.

Diagnosing: While its running in the loop, there are no further requests done to evilginx, so maybe the issue is somewhere else?

**Comment by gsmthconsult** [comment] 2022-03-30 16:44
I'm guessing the issue is from office365 itself

**Comment by gsmthconsult** [comment] 2022-03-30 16:45
they probably patched that bit to cause that problem

**Comment by Web3villian666** [comment] 2022-04-05 01:18
I had similar issues stuck on the first sign in page that's the old phishlets.... attually I got the latest .yaml off the author y'all can reach out to him on icq @mrgretzky to get issues fixed if needed.

**Comment by rickyrik001** [comment] 2022-04-08 22:30
If you need help regarding o365 can reach me on telegram @Ricky_rik1

**Comment by 456478** [comment] 2022-04-13 22:51
I was missing the right sub filter. It wouldn't get endlessly stuck but it was loading that page too long.
After adding the right sub filter, the trying to sign you in page proceeds almost instantly and I'm sure it wouldn't get stuck in the loop

**Comment by squodgeface** [comment] 2022-04-18 12:47
> I was missing the right sub filter. It wouldn't get endlessly stuck but it was loading that page too long. After adding the right sub filter, the trying to sign you in page proceeds almost instantly and I'm sure it wouldn't get stuck in the loop

Could you please copy the right sub filter, thanks. 
Does this allow EG to grab the o365 cookies?

**Comment by klumren1** [comment] 2022-09-01 08:50
> If you need help regarding o365 can reach me on telegram @Ricky_rik1

This guys a ripper be careful

**Comment by authverify** [comment] 2022-09-12 11:17
@d4rk9t contact me for help... I have cookie grabber for google and o365

**Comment by lacylau157** [comment] 2022-09-12 11:18
Ok how do I go about it ??

**Comment by lacylau157** [comment] 2022-09-12 11:20
I just messaged your on ICQ

**Comment by CharlesMor1580** [comment] 2022-09-28 20:34
> > If you need help regarding o365 can reach me on telegram @Ricky_rik1
> 
> This guys a ripper be careful

Are you sure please explain

**Comment by rickyrik001** [comment] 2022-09-29 20:06
> > > If you need help regarding o365 can reach me on telegram @Ricky_rik1
> > 
> > 
> > This guys a ripper be careful
> 
> Are you sure please explain
I haven't rip him ,he doesn't no how to use evilginx ,he doesn't know any command ,I tried to help him,but I am not here to help him all the time

**Comment by Support-1535** [comment] 2022-11-03 21:03
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!

If you want expedited help and have the assistance of many professional people, join our private group. Contact us support@evilginx2.com to give you access to the group.

**Comment by klumren1** [comment] 2022-11-13 13:29
> > > If you need help regarding o365 can reach me on telegram @Ricky_rik1
> > 
> > 
> > This guys a ripper be careful
> 
> Are you sure please explain I haven't rip him ,he doesn't no how to use evilginx ,he doesn't know any command ,I tried to help him,but I am not here to help him all the time

Okay if not ripped then when ask you to help me you block me

**Comment by klumren1** [comment] 2022-11-13 14:37
Misunderstanding Ricky fixed my issues.

**Closed** 2023-05-10 11:57 UTC
