### ISSUE TITLE
Phishlets redirecting to youtube

### ISSUE THREAD

**Issue by Bivin4205** [kgretzky/evilginx2#830] opened 2022-09-05 12:14 UTC
Hi Team, 

I have setup the script and it's working for me from last two days.

But today when i am trying to open the Phishlets URL its redirecting to youtube and i am unable to see any login page.

i am getting this error in the log 

blacklist: request from IP address '37.228.250.42' was blocked

outlook or officeo365 login page not even opening.

I have demo by tomorrow evening 

Thanks and Regards 
Bivin

**Comment by Bivin4205** [comment] 2022-09-05 14:29
Yes . I used the below command.

lures edit 0 redirect_url https://outlook.office.com/mail/

**Comment by Bivin4205** [comment] 2022-09-06 16:16
When ever i trying to login i am getting this log.

[war] blacklist: request from ip address '37.228.250.42' was blocked

**Comment by JM-Lemmi** [comment] 2022-09-07 09:07
The error says right there. Your IP is on the blacklist. See `blacklist` command

**Comment by Bivin4205** [comment] 2022-09-07 10:02
Hi JM-Lemmi,

How can we whitelist the same ?? 
During the installation time I have done the below command 

Blacklist unauth.

**Comment by JM-Lemmi** [comment] 2022-09-07 11:06
Then its working correctly. This is not a bug. Please do not ask for techsupport in the issues, as the template already said!

#### REPORT ONLY BUGS OR FEATURE SUGGESTIONS.

**Comment by Bivin4205** [comment] 2022-09-07 11:21
Sorry to say that i followed correct document but still not woking and its seem to bug for me.

**Comment by Bivin4205** [comment] 2022-09-07 11:27
And each time i am getting a different error. 

Now I am getting Microsoft error after I am trying to login to outlook or o365

![Screenshot 2022-09-07 at 12 26 16 p m](https://user-images.githubusercontent.com/101496561/188867442-d8909352-c44a-4dc1-84f0-04361a518dfc.png)

**Comment by Support-1535** [comment] 2022-10-26 22:16
Hello! If you were already able to resolve your doubts and achieve your goals, close the issue so that we know which ones are pending.

Thank you!

**Closed** 2023-05-10 11:33 UTC
