### ISSUE TITLE
failed to load certifacte file

### ISSUE THREAD

**Issue by R3dFalcon** [kgretzky/evilginx2#91] opened 2018-11-12 19:45 UTC
I know this has been related a lot here, but none of the topics exactly fits my problem. I get the following warning :

[20:31:57] [war] failed to load certificate files for phishlet 'outlook', domain '**********': open /root/.evilginx/crt/**********/outlook.crt: no such file or directory

After that, I get several time Error 400.
I don't get what that missing file or directory is supposed to be...
Thank you to anyone who takes the time to answer !

**Comment by kgretzky** [comment] 2018-11-12 20:30
This is a dupe of #89 again. Nameserver is not set up and it is unable to obtain certificates.
Read the blog post please.

**Closed by kgretzky** 2018-11-12 20:30 UTC
